name: release
on:
  push:
    tags:
      - '*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Read Versions File
        id: versions
        uses: falti/dotenv-action@v0.2.8
        with:
          path: versions
          log-variables: true
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:package"
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            GO_VERSION=${{ steps.versions.outputs.go_version }}
            DLV_VERSION=${{ steps.versions.outputs.dlv_version }}
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.versions.outputs.dlv_version }}-${{ steps.versions.outputs.delve_debugger_version }}
            ghcr.io/${{ github.repository }}:latest
